language: java
dist: trusty
sudo: false
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
    - $HOME/.m2

# Upload coverage report
after_success:
  - bash <(curl -s https://codecov.io/bash)
